name: CI

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19
    - name: Check out code into the Go module directory
      run: |
        mkdir -p $HOME/go/src/github.com/${{ github.repository }}
        rsync -az --exclude '.git' ${{ github.workspace }}/* $HOME/go/src/github.com/${{ github.repository }}
        echo "GOPATH=$HOME/go" >> $GITHUB_ENV
        echo "$HOME/go/bin" >> $GITHUB_PATH
    - name: Install golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.52.2
    - name: Run golangci-lint
      run: |
        golangci-lint run --config .golangci.yml
    - name: Test with go test
      run: |
        go test ./...